### PR TITLE
Replace time 0.1 with httpdate

### LINKED ISSUE #21: Update to time 0.2

### PR DESCRIPTION
**Pull request by paolobarbolini**
Closes #21

### CODE REVIEW

**Comment by dekellum** [comment]
Thanks for attempting this and sorry for the delayed response.  Note that many places that use hyperx are also using hyper. As of 0.13.7, hyper has a dependency on time 0.1, and I'm not sure updating hyperx to time 0.2 would be compatible in all cases?  At the very least it would force a duplicate.  This inclines me to defer this to a subsequent major or minor release of hyperx, and possibly once hyper updates.

**Comment by paolobarbolini** [comment]
The latest hyper doesn't depend on `time` anymore https://github.com/hyperium/hyper/commit/25a05894b97eca5b5e486cf2f4245e638464d318#diff-80398c5faae3c069e4e6aa2ed11b28c0

**Comment by dekellum** [comment]
Okay, thanks, I didn't see that change.  Will at least defer until the hyper change is released. Also now wondering if httpdate, without looking at this in detail, is a better dependency for hyperx?

**Comment by peddermaster2** [comment]
`hyper = "0.13.8"` does not depends on `time` is released.

**Comment by paolobarbolini** [comment]
I had some more time to work on this and now it uses `httpdate` just like the latest hyper does

**Comment by dekellum** [comment]
Thanks for this. I tweaked this further in #24, to use `httpdate::HttpDate` as the inner type (instead of `SystemTime` used here).  Please take a look @paolobarbolini and comment if you have any concerns?

**Pull request merged**
